apiVersion: dp.wso2.com/v1alpha1
kind: API
metadata:
  name: shopkart-api
  namespace: shopkart
spec:
  apiName: ShopKartProductAPI
  apiVersion: 1.0.0
  apiType: REST
  basePath: /ShopKartProductAPI/1.0.0
  organization: default
  definition:
    inline:
      openAPISpec: |
        openapi: 3.0.1
        info:
          title: ShopKart Product API
          version: 1.0.0
        paths:
          /products:
            get:
              responses:
                "200":
                  description: Successfully retrieved the product list.
              summary: Get list of ShopKart products
  production:
    - httpRouteRefs:
        - prod-productapi-route
  sandbox:
    - httpRouteRefs:
        - sand-productapi-route

  mode: privateJet
