apiVersion: dp.wso2.com/v1alpha1
kind: API
metadata:
  name: shopkart-api
  namespace: shopkart
spec:
  apiName: ShopKartProductAPI
  apiVersion: 1.0.0
  apiType: REST
  basePath: /ShopKartProductAPI/1.0.0
  organization: admin
  definition:
    inline:
      openAPISpec: |
        openapi: 3.0.1
        info:
          title: ShopKart Product API
          version: 1.0.0
        paths:
          /products:
            get:
              summary: List all available products from ShopKart
              responses:
                "200":
                  description: OK
  production:
    - inline:
        endpointConfigurations:
          production:
            url: https://run.mocky.io/v3/5988d96d-16ad-4bb0-bc9c-92a57480a303
  sandbox:
    - inline:
        endpointConfigurations:
          sandbox:
            url: https://run.mocky.io/v3/5988d96d-16ad-4bb0-bc9c-92a57480a303
  mode: privateJet
