apiVersion: batch/v1
kind: Job
metadata:
  name: shopkart-api
  namespace: shopkart
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "20"
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: apictl
          image: alpine:3.20
          env:
            - name: API_PATH
              value: /prod/ShopKartAPI
            - name: APIM_HOST
              valueFrom:
                secretKeyRef:
                  name: apim-prod-credentials
                  key: APIM_HOST
            - name: APIM_USER
              valueFrom:
                secretKeyRef:
                  name: apim-prod-credentials
                  key: APIM_USER
            - name: APIM_PASS
              valueFrom:
                secretKeyRef:
                  name: apim-prod-credentials
                  key: APIM_PASS
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -euo pipefail
              apk add --no-cache curl tar jq ca-certificates
              curl -L -o /tmp/apictl.tgz https://github.com/wso2/product-apim-tooling/releases/download/v4.5.0/apictl-4.5.0-linux-amd64.tar.gz
              tar -xzf /tmp/apictl.tgz -C /usr/local/bin --strip-components=1 apictl/apictl
              chmod +x /usr/local/bin/apictl
              apictl version

              echo "==> Register + login to PROD Publisher"
              apictl add env prod --apim "https://${APIM_HOST}"
              apictl login prod -u "${APIM_USER}" -p "${APIM_PASS}" --insecure

              echo "==> Import/Update ShopKartAPI from ${API_PATH}"
              apictl import api -f "${API_PATH}" -e prod --preserve-provider=false --update --insecure

              echo "Import API to Prod environment is successdul."
