apiVersion: batch/v1
kind: Job
metadata:
  name: shopkartapi-publish-v2
  namespace: shopkart
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: apictl
          image: bitnami/git:2.45.2  # Has Git, Curl, Tar, CA Certs pre-installed
          env:
            - name: APIM_HOST
              valueFrom:
                secretKeyRef:
                  name: apim-prod-credentials
                  key: APIM_HOST
            - name: APIM_USER
              valueFrom:
                secretKeyRef:
                  name: apim-prod-credentials
                  key: APIM_USER
            - name: APIM_PASS
              valueFrom:
                secretKeyRef:
                  name: apim-prod-credentials
                  key: APIM_PASS
          command: ["/bin/bash", "-lc"]
          args:
            - |
              set -euo pipefail

              export HOME=/tmp/apictl-home
              mkdir -p /tmp/bin "$HOME"

              echo "==> Install apictl"
              APICTL_VERSION=4.5.0
              ARCH="$(uname -m)"
              case "$ARCH" in
                x86_64|amd64) APICTL_TARBALL="apictl-${APICTL_VERSION}-linux-amd64.tar.gz" ;;
                aarch64|arm64) APICTL_TARBALL="apictl-${APICTL_VERSION}-linux-arm64.tar.gz" ;;
                *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
              esac
              curl -L -o /tmp/apictl.tgz "https://github.com/wso2/product-apim-tooling/releases/download/v${APICTL_VERSION}/${APICTL_TARBALL}"
              echo "==> downloaded"
              tar -xzf /tmp/apictl.tgz -C /tmp/bin --strip-components=1 apictl/apictl
              echo "==> tar extracted"
              chmod +x /tmp/bin/apictl
              echo "==> chmod done"
              export PATH="/tmp/bin:$PATH"
              echo "==> export done"
              apictl version
              echo $ARCH
              
              echo "==> Using API project from ArgoCD workspace"
              cd /workspace/prod/ShopKartAPI

              echo "==> Login to PROD"
              apictl add env prod --apim "https://${APIM_HOST}" || true
              apictl login prod -u "${APIM_USER}" -p "${APIM_PASS}" --insecure

              echo "==> Import/Update API to PROD from $(pwd)"
              apictl import api -f . -e prod --preserve-provider=false --update --insecure

              echo "Import to PROD completed."
          volumeMounts:
            - name: argocd-workspace
              mountPath: /workspace
      volumes:
        - name: argocd-workspace
          hostPath:
            path: /tmp/argocd-workspace
            type: DirectoryOrCreate
