apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopkart
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: shopkart
  source:
    repoURL: https://github.com/Tharanidk/ShopKart.git
    targetRevision: main
    path: prod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  ignoreDifferences:
    - group: dp.wso2.com
      kind: API
      name: shopkart-api
      namespace: shopkart
      jsonPointers:
        - /status
        - /metadata/annotations/argocd.argoproj.io~1tracking-id
        - /metadata/annotations
        - /spec/definition
